spring.application.name=demo
crypto.binance.klines-url=https://api.binance.com/api/v3/klines
crypto.binance.limit=365
market.yahoo.chart-url-template=https://query1.finance.yahoo.com/v8/finance/chart/{assetSymbol}
spark.master=local[*]
spark.mongodb.connection-string=mongodb://localhost:27017
spark.mongodb.database=test
